const {AsyncLocalStorage}=require('node:async_hooks');
const requestScope=new AsyncLocalStorage();
function context(){const ctx=requestScope.getStore();if(!ctx)throw new Error('Sin contexto de transacción.');return ctx;}
const all=async name=>[...context().stores[name].values()].map(v=>structuredClone(v));
const get=async (name,key)=>{const v=context().stores[name].get(String(key));return v===undefined?undefined:structuredClone(v);};
async function put(name,value){
 const ctx=context();const row=structuredClone(value);
 if(name==='users'||name==='subjects'){
   if(row.id===undefined||row.id===null){row.id=ctx.nextId?await ctx.nextId():++ctx.lastId;}
   ctx.stores[name].set(String(row.id),row);
   ctx.dirty.set(name+'|'+row.id,{name,key:String(row.id),row});return row.id;
 }
 if(typeof row.key!=='string'||!row.key)throw new Error('Registro sin clave.');
 ctx.stores[name].set(row.key,row);ctx.dirty.set(name+'|'+row.key,{name,key:row.key,row});return row.key;
}
async function remove(name,key){const ctx=context();ctx.stores[name].delete(String(key));ctx.dirty.set(name+'|'+String(key),{name,key:String(key),row:null});}
const CURRENT_YEAR=Number(new Intl.DateTimeFormat('en-US',{year:'numeric',timeZone:'America/Guatemala'}).format(new Date()));
const YEAR=Math.max(CURRENT_YEAR,Number(process.env.SCHOOL_YEAR)||CURRENT_YEAR);
const GRADES=[{code:'B1',name:'1.º básico',section:'Básico'},{code:'B2',name:'2.º básico',section:'Básico'},{code:'B3',name:'3.º básico',section:'Básico'},{code:'P4',name:'4.º perito',section:'Perito en Administración'},{code:'P5',name:'5.º perito',section:'Perito en Administración'},{code:'P6',name:'6.º perito',section:'Perito en Administración'},{code:'C4',name:'4.º bachillerato',section:'Bachillerato en Ciencias y Letras con Orientación en Computación'},{code:'C5',name:'5.º bachillerato',section:'Bachillerato en Ciencias y Letras con Orientación en Computación'}];
const BASIC=['Matemática','Cultura e Idioma Maya, Garífuna o Xinca','Comunicación y Lenguaje Idioma Español','Comunicación y Lenguaje, Idioma Extranjero','Ciencias Naturales','Ciencias Sociales y Ciudadanía','Educación y Expresión Artística','Emprendimiento para la Productividad','Tecnologías del Aprendizaje y la Comunicación','Educación Física'];
const SUBJECTS={B1:BASIC,B2:BASIC,B3:BASIC,C4:['Lengua y Literatura 4','Comunicación y Lenguaje L3 Inglés Técnico 4','Matemática 4','Física','Ciencias Sociales y Formación Ciudadana 4','Filosofía','Expresión Artística','Educación Física','Computación Aplicada','Laboratorio I','Sistemas e Instalación de Software','Contabilidad General'],C5:['Lengua y Literatura 5','Comunicación y Lenguaje L3 Inglés Técnico 5','Matemática 5','Estadística Descriptiva','Biología','Química','Ciencias Sociales y Formación Ciudadana 5','Ética Profesional y Relaciones Humanas','Reparación y Soporte Técnico','Laboratorio II','Seminario','Práctica Supervisada']};
const subjectOrder=(a,b)=>(a.order??a.id)-(b.order??b.id)||a.id-b.id;
const validGrade=v=>Number.isFinite(v)&&v>=0&&v<=100;
const meanValues=values=>{const present=values.filter(validGrade);return present.length?present.reduce((sum,v)=>sum+Number(v),0)/present.length:null;};
const round2=v=>v===null?null:Math.round((v+Number.EPSILON)*100)/100;
const allPresent=values=>values.length>0&&values.every(validGrade);

const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const periodName=n=>['','I BIMESTRE','II BIMESTRE','III BIMESTRE','IV BIMESTRE'][n]||'';
const scoreText=v=>v===null||v===undefined?'—':Number(v).toFixed(2).replace(/\.00$/,'');
const scoreTone=v=>v===null||v===undefined?'score-pending':Number(v)<60?'score-low':Number(v)<75?'score-mid':'score-high';


function legacySurname(name){if(String(name||'').includes(','))return String(name).split(',')[0].trim();const parts=String(name||'').trim().split(/\s+/).filter(Boolean);return parts.length>=4?parts.slice(-2).join(' '):parts.length>=2?parts.slice(-1).join(' '):parts.join(' ');}
function lastNameOf(person){return person.last_names||legacySurname(person.full_name);}
function firstNameOf(person){if(person.first_names)return person.first_names;if(String(person.full_name||'').includes(','))return String(person.full_name).split(',').slice(1).join(',').trim();const value=String(person.full_name||'').trim().split(/\s+/);return value.slice(0,Math.max(1,value.length-(value.length>=4?2:1))).join(' ');}
function academicName(person){return person.last_names&&person.first_names?`${person.last_names}, ${person.first_names}`:person.full_name;}
function bySurname(a,b){return lastNameOf(a).localeCompare(lastNameOf(b),'es',{sensitivity:'base'})||firstNameOf(a).localeCompare(firstNameOf(b),'es',{sensitivity:'base'})||a.id-b.id;}
function onlyOwnGrade(actor,target){if(actor.role==='admin')return;if(actor.role!=='teacher'||target.role!=='student'||target.grade_code!==actor.grade_code)fail('Solo puedes administrar estudiantes de tu propio grado guía.');}
function studentParts(body){const first=text(body.first_names,'Nombres',90),last=text(body.last_names,'Apellidos',90);return{first_names:first,last_names:last,full_name:`${last}, ${first}`};}
function fail(text){throw new Error(text);}
function text(v,label,max=120){if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail(`${label}: escribe un valor válido.`);return v.trim().replace(/\s+/g,' ');}
function grade(v){if(!GRADES.some(g=>g.code===v))fail('Selecciona un grado válido.');return v;}
function period(v){const p=Number(v);if(!Number.isInteger(p)||p<1||p>4)fail('Selecciona un bimestre válido.');return p;}
function slimName(name){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z]/g,'').slice(0,2).toLowerCase()||'sd';}
function digits(size=4){return String(require('node:crypto').randomInt(0,10**size)).padStart(size,'0');}
function generatePassword(name,gradeCode){const crypto=require('node:crypto');const x=slimName(name);const initials=x[0].toUpperCase()+x.slice(1);const gradePart=String(gradeCode||'SD').replace(/[^A-Za-z0-9]/g,'').slice(0,3).toUpperCase()||'SD';const alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ';let suffix='';for(let i=0;i<6;i++)suffix+=alphabet[crypto.randomInt(alphabet.length)];return initials+gradePart+'-'+suffix;}
const skey=(sid,subject,p)=>`${YEAR}|${p}|${sid}|${subject}`;
const pkey=(sid,p)=>`${YEAR}|${sid}|${p}`;
function admin(u){if(u.role!=='admin')fail('Esta acción corresponde exclusivamente a dirección.');}
function guide(u,g){if(u.role!=='admin'&&!(u.role==='teacher'&&u.grade_code===g))fail('Solo el docente guía del grado o dirección pueden modificar esas notas.');}
function studentOf(g,id,users){const u=users.find(x=>x.id===Number(id)&&x.role==='student'&&x.active&&x.grade_code===g);if(!u)fail('El estudiante no pertenece a este grado.');return u;}
const publicUser=u=>{const{password,...rest}=u;return rest;};
async function effectiveStatus(g,sid,p){const individual=await get('studentPeriods',pkey(sid,p));if(individual)return individual.state;const legacy=await get('periods',`${YEAR}|${g}|${p}`);return legacy?.state||'draft';}
async function ensureCardHasScores(g,sid,p){const [subjects,scores]=await Promise.all([all('subjects'),all('scores')]);const ids=new Set(subjects.filter(s=>s.active&&s.grade_code===g).map(s=>s.id));if(!ids.size)fail('No hay materias registradas para este grado.');const filled=scores.filter(s=>s.student_id===sid&&s.year===YEAR&&s.period===p&&ids.has(s.subject_id));if(!filled.length)fail(`Ingresa al menos una nota de ${periodName(p)} antes de enviarla. Puedes dejar las demás materias en blanco.`);return filled.length;}
async function executeOperation(op,{body={},query={}}={},actor){
if(op==='me')return{user:publicUser(actor),year:YEAR};
if(op==='users'){if(!['admin','teacher'].includes(actor.role))fail('Sin autorización.');const users=(await all('users')).filter(u=>u.role!=='admin'&&(actor.role==='admin'||u.role==='student'&&u.grade_code===actor.grade_code)).map(publicUser).sort((a,b)=>a.role===b.role?(a.role==='student'?bySurname(a,b):a.full_name.localeCompare(b.full_name,'es')):a.role.localeCompare(b.role));return{users};}
if(op==='createUser'){if(!['student','teacher'].includes(body.role))fail('Tipo de cuenta inválido.');if(actor.role==='teacher'&&body.role!=='student')fail('El docente solo puede registrar alumnos.');if(actor.role!=='teacher'&&actor.role!=='admin')fail('Sin autorización.');const g=actor.role==='teacher'?actor.grade_code:grade(body.grade);if(actor.role==='teacher'&&body.grade&&body.grade!==g)fail('Solo puedes registrar estudiantes de tu grado.');const details=body.role==='student'?studentParts(body):{full_name:text(body.name,'Nombre completo')};const existing=await all('users');const base=slimName(details.first_names||details.full_name)+YEAR;let username=base,n=2;while(existing.some(u=>u.username.toLowerCase()===username.toLowerCase()))username=base+'-'+n++;const password=generatePassword(details.first_names||details.full_name,g);const id=await put('users',{username,password,...details,role:body.role,grade_code:g,delinquent:false,active:true,token_version:0,created_by:actor.id,created_at:new Date().toISOString()});return{account:{id,username,full_name:details.full_name,grade_code:g,role:body.role},password};}
if(op==='credentials'){const target=await get('users',Number(body.id));if(!target||target.role==='admin'||!target.active)fail('Cuenta no disponible.');if(actor.role!=='admin'&&!(actor.role==='teacher'&&target.role==='student'&&target.grade_code===actor.grade_code))fail('Solo dirección o el docente guía del estudiante pueden consultar sus credenciales.');return{username:target.username,password:target.password};}
if(op==='resetPassword'){const target=await get('users',Number(body.id));if(!target||target.role==='admin'||!target.active)fail('Cuenta no disponible.');if(actor.role!=='admin'&&!(actor.role==='teacher'&&target.role==='student'&&target.grade_code===actor.grade_code))fail('No puedes restablecer esta contraseña.');target.password=generatePassword(target.first_names||firstNameOf(target),target.grade_code);target.token_version++;await put('users',target);return{username:target.username,password:target.password};}
if(op==='updateUser'){const target=await get('users',Number(body.id));if(!target||target.role==='admin')fail('Cuenta no disponible.');onlyOwnGrade(actor,target);if(body.action==='debt'&&target.role==='student'){target.delinquent=!!body.value;target.debt_updated_by=actor.id;target.debt_updated_at=new Date().toISOString();}else if(body.action==='rename'&&target.role==='student'){const names=studentParts(body);Object.assign(target,names);target.name_updated_by=actor.id;}else if(body.action==='grade'&&actor.role==='admin'){const next=grade(body.grade);if(target.grade_code!==next&&target.role==='student'){const oldScores=await all('scores'),oldStatuses=await all('studentPeriods');for(const row of oldScores.filter(x=>x.student_id===target.id&&x.year===YEAR))await remove('scores',row.key);for(const row of oldStatuses.filter(x=>x.student_id===target.id&&x.year===YEAR))await remove('studentPeriods',row.key);}target.grade_code=next;target.token_version++;}else if(body.action==='active'&&actor.role==='admin'){target.active=!!body.value;target.token_version++;}else fail('Cambio no permitido para tu cuenta.');await put('users',target);return{success:true};}
if(op==='deleteUser'){const target=await get('users',Number(body.id));if(!target||target.role==='admin')fail('Cuenta no disponible.');onlyOwnGrade(actor,target);if(target.role==='student'){const[notes,states]=await Promise.all([all('scores'),all('studentPeriods')]);for(const x of notes.filter(x=>x.student_id===target.id))await remove('scores',x.key);for(const x of states.filter(x=>x.student_id===target.id))await remove('studentPeriods',x.key);}await remove('users',target.id);return{success:true};}
if(op==='changeOwnPassword'){
  const current=body.current,newPassword=body.password,confirmation=body.confirm;
  if(typeof current!=='string'||current!==actor.password)fail('La contraseña actual es incorrecta.');
  if(typeof newPassword!=='string'||newPassword.length<8||newPassword.length>64||newPassword.trim()!==newPassword||!/[A-Za-zÁÉÍÓÚáéíóúÑñ]/.test(newPassword)||!/[0-9]/.test(newPassword))fail('La nueva contraseña debe tener de 8 a 64 caracteres, incluir letras y números y no tener espacios al principio ni al final.');
  if(newPassword!==confirmation)fail('La confirmación no coincide con la nueva contraseña.');
  if(newPassword===current)fail('La nueva contraseña debe ser diferente de la actual.');
  actor.password=newPassword;actor.token_version=(actor.token_version||0)+1;
  await put('users',actor);return{success:true};
}
if(op==='changeAdminPassword'){admin(actor);if(body.current!==actor.password)fail('La contraseña actual es incorrecta.');const newPassword=text(body.password,'Nueva contraseña',128);if(newPassword.length<12)fail('La contraseña de dirección debe tener al menos 12 caracteres.');actor.password=newPassword;actor.token_version++;await put('users',actor);return{success:true};}
if(op==='subjects'){if(!['admin','teacher'].includes(actor.role))fail('Sin autorización.');return{subjects:(await all('subjects')).filter(s=>!s.deleted).sort((a,b)=>a.grade_code.localeCompare(b.grade_code)||subjectOrder(a,b))};}
if(op==='addSubject'){admin(actor);const g=grade(body.grade),name=text(body.name,'Materia',100);if((await all('subjects')).some(s=>!s.deleted&&s.grade_code===g&&norm(s.name)===norm(name)))fail('Esa materia ya existe en el grado.');const own=(await all('subjects')).filter(s=>!s.deleted&&s.grade_code===g);await put('subjects',{grade_code:g,name,active:true,order:own.reduce((max,s)=>Math.max(max,s.order||0),0)+1});return{success:true};}
if(op==='editSubject'){admin(actor);const id=Number(body.id),target=await get('subjects',id);if(!target||target.deleted)fail('Materia no encontrada.');const classmates=(await all('subjects')).filter(s=>!s.deleted&&s.grade_code===target.grade_code).sort(subjectOrder);if(body.action==='rename'){const name=text(body.name,'Nombre de la materia',100);if(classmates.some(s=>s.id!==id&&norm(s.name)===norm(name)))fail('Ya existe otra materia con ese nombre en el grado.');target.name=name;await put('subjects',target);}else if(body.action==='move'){const index=classmates.findIndex(s=>s.id===id),other=classmates[index+(body.direction==='up'?-1:1)];if(!other)fail('La materia ya está en ese extremo.');for(let i=0;i<classmates.length;i++){classmates[i].order=i+1;await put('subjects',classmates[i]);}const current=classmates[index],previous=current.order;current.order=other.order;other.order=previous;await put('subjects',current);await put('subjects',other);}else if(body.action==='visibility'){target.active=!!body.active;await put('subjects',target);}else if(body.action==='delete'){const related=(await all('scores')).filter(s=>s.subject_id===id);for(const row of related)await remove('scores',row.key);target.deleted=true;target.active=false;target.deleted_at=new Date().toISOString();await put('subjects',target);const remaining=classmates.filter(s=>s.id!==id);for(let i=0;i<remaining.length;i++){remaining[i].order=i+1;await put('subjects',remaining[i]);}return{success:true,removedGrades:related.length};}else fail('Cambio no permitido.');return{success:true};}
if(op==='debtList'){if(!['teacher','admin'].includes(actor.role))fail('Sin autorización.');return{students:(await all('users')).filter(u=>u.role==='student'&&u.active&&u.delinquent&&(actor.role==='admin'||u.grade_code===actor.grade_code)).map(publicUser).sort((a,b)=>a.grade_code.localeCompare(b.grade_code)||bySurname(a,b))};}
if(op==='studentList'){if(!['teacher','admin'].includes(actor.role))fail('Sin autorización.');const g=grade(query.grade);const students=(await all('users')).filter(u=>u.role==='student'&&u.active&&u.grade_code===g).sort(bySurname);return{students:students.map(u=>({id:u.id,full_name:academicName(u),grade_code:u.grade_code}))};}
if(op==='studentCard'){
if(!['teacher','admin'].includes(actor.role))fail('Sin autorización.');const g=grade(query.grade),sid=Number(query.studentId),students=await all('users'),student=studentOf(g,sid,students),other=actor.role==='teacher'&&actor.grade_code!==g;
const [subjects,scores,individuals,legacy]=await Promise.all([all('subjects'),all('scores'),all('studentPeriods'),all('periods')]);
const classes=subjects.filter(s=>s.active&&s.grade_code===g).sort(subjectOrder);const statuses=Array.from({length:4},(_,i)=>{const p=i+1;const specific=individuals.find(s=>s.key===pkey(sid,p));return specific?.state||legacy.find(s=>s.key===`${YEAR}|${g}|${p}`)?.state||'draft';});
return{student:{id:sid,full_name:student.full_name},subjects:classes.map(s=>({id:s.id,name:s.name})),statuses:other?statuses.map(v=>v==='published'?v:'unavailable'):statuses,scores:classes.map(s=>({subjectId:s.id,values:[1,2,3,4].map((p,i)=>{if(other&&statuses[i]!=='published')return null;const match=scores.find(n=>n.key===skey(sid,s.id,p));return match?match.score:null;})})),canEdit:!other,grade:g};}
if(op==='saveStudentCard'){
const g=grade(body.grade),p=period(body.period),sid=Number(body.studentId);guide(actor,g);studentOf(g,sid,await all('users'));if(await effectiveStatus(g,sid,p)!=='draft')fail('Este boletín está enviado o publicado. Dirección debe devolverlo a borrador para corregir.');
const classes=(await all('subjects')).filter(s=>s.active&&s.grade_code===g).sort(subjectOrder);const ids=new Set(classes.map(s=>s.id));if(!Array.isArray(body.values)||body.values.length!==classes.length)fail('Falta alguna materia en la tarjeta.');const rows=new Set();for(const item of body.values){const id=Number(item.subjectId),v=item.score;if(!ids.has(id)||rows.has(id))fail('Hay una materia inválida o repetida.');rows.add(id);if(v!==null&&(!Number.isFinite(v)||v<0||v>100))fail('Las notas deben estar entre 0 y 100.');}
for(const item of body.values){const id=Number(item.subjectId),key=skey(sid,id,p);if(item.score===null)await remove('scores',key);else await put('scores',{key,student_id:sid,subject_id:id,year:YEAR,period:p,score:item.score,updated_by:actor.id});}return{success:true};}
if(op==='submitStudent'){
const g=grade(body.grade),p=period(body.period),sid=Number(body.studentId);guide(actor,g);studentOf(g,sid,await all('users'));if(await effectiveStatus(g,sid,p)!=='draft')fail('Las notas ya fueron enviadas o publicadas.');await ensureCardHasScores(g,sid,p);await put('studentPeriods',{key:pkey(sid,p),student_id:sid,grade_code:g,period:p,year:YEAR,state:'submitted',submitted_at:new Date().toISOString(),published_at:null});return{success:true};}
if(op==='submitGrade'){
const g=grade(body.grade),p=period(body.period);guide(actor,g);const students=(await all('users')).filter(u=>u.role==='student'&&u.active&&u.grade_code===g);if(!students.length)fail('No hay estudiantes activos en este grado.');const next=[],missing=[];for(const student of students){if(await effectiveStatus(g,student.id,p)!=='draft')continue;try{await ensureCardHasScores(g,student.id,p);next.push(student);}catch(e){missing.push(student.full_name);}}if(!next.length)fail(missing.length?`Todavía no hay notas registradas de: ${missing.slice(0,4).join(', ')}.`:'No hay notas nuevas pendientes de enviar.');for(const student of next)await put('studentPeriods',{key:pkey(student.id,p),student_id:student.id,grade_code:g,period:p,year:YEAR,state:'submitted',submitted_at:new Date().toISOString(),published_at:null});return{sent:next.length,skipped:missing.length};}
if(op==='reopenStudent'){admin(actor);const g=grade(body.grade),p=period(body.period),sid=Number(body.studentId);studentOf(g,sid,await all('users'));await put('studentPeriods',{key:pkey(sid,p),student_id:sid,grade_code:g,period:p,year:YEAR,state:'draft',submitted_at:null,published_at:null});return{success:true};}
if(op==='publishStudent'){admin(actor);const g=grade(body.grade),p=period(body.period),sid=Number(body.studentId);studentOf(g,sid,await all('users'));if(await effectiveStatus(g,sid,p)!=='submitted')fail('Para publicar, primero deben enviarse las notas de este alumno y bimestre a dirección.');await ensureCardHasScores(g,sid,p);await put('studentPeriods',{key:pkey(sid,p),student_id:sid,grade_code:g,period:p,year:YEAR,state:'published',submitted_at:new Date().toISOString(),published_at:new Date().toISOString()});return{success:true};}
if(op==='publishAll'){admin(actor);const[students,personal,old]=await Promise.all([all('users'),all('studentPeriods'),all('periods')]);const targets=[];for(const student of students.filter(u=>u.role==='student'&&u.active)){for(let p=1;p<=4;p++){const specific=personal.find(x=>x.key===pkey(student.id,p));const status=specific?.state||old.find(x=>x.key===`${YEAR}|${student.grade_code}|${p}`)?.state||'draft';if(status==='submitted'){await ensureCardHasScores(student.grade_code,student.id,p);targets.push({student,p});}}}if(!targets.length)fail('No hay boletines enviados pendientes de publicación.');for(const{student,p}of targets)await put('studentPeriods',{key:pkey(student.id,p),student_id:student.id,grade_code:student.grade_code,period:p,year:YEAR,state:'published',submitted_at:new Date().toISOString(),published_at:new Date().toISOString()});return{published:targets.length};}
if(op==='honors'){
admin(actor);
const [people,classes,notes,personal,legacy]=await Promise.all([all('users'),all('subjects'),all('scores'),all('studentPeriods'),all('periods')]);
const members=people.filter(u=>u.role==='student'&&u.active);
const subjects=classes.filter(s=>s.active&&!s.deleted);
const gradeRows=GRADES.map(g=>{
const pupils=members.filter(u=>u.grade_code===g.code);
const subs=subjects.filter(s=>s.grade_code===g.code);
const marks=notes.filter(n=>n.year===YEAR&&subs.some(s=>s.id===n.subject_id));
const candidates=pupils.map(person=>{
const matching=marks.filter(n=>n.student_id===person.id&&validGrade(n.score));
const averages=[1,2,3,4].map(q=>meanValues(matching.filter(n=>n.period===q).map(n=>n.score)));
const total=subs.length*4;
return{id:person.id,name:academicName(person),grade:g.code,average:round2(meanValues(averages)),periods:averages.map(round2),count:matching.length,total,complete:total>0&&matching.length===total};
}).filter(c=>c.average!==null).sort((a,b)=>b.average-a.average||a.name.localeCompare(b.name,'es'));
const top=candidates[0]?.average??null;
const leaders=top===null?[]:candidates.filter(c=>c.average===top);
const finished=pupils.length>0&&subs.length>0&&pupils.every(p=>candidates.some(c=>c.id===p.id&&c.complete)&&[1,2,3,4].every(q=>(personal.find(v=>v.key===pkey(p.id,q))?.state||legacy.find(v=>v.key===`${YEAR}|${g.code}|${q}`)?.state)==='published'));
return{...g,studentCount:pupils.length,subjectCount:subs.length,finished,candidates,top,leaders};
});
const allCandidates=gradeRows.flatMap(row=>row.candidates).sort((a,b)=>b.average-a.average||a.name.localeCompare(b.name,'es'));
const top=allCandidates[0]?.average??null;
return{grades:gradeRows,overall:top===null?[]:allCandidates.filter(c=>c.average===top),overallTop:top,final:gradeRows.some(g=>g.studentCount>0)&&gradeRows.filter(g=>g.studentCount>0).every(g=>g.finished)};
}
if(op==='overview'){if(!['admin','teacher'].includes(actor.role))fail('Sin autorización.');const[users,personal,legacy,scores,subjects]=await Promise.all([all('users'),all('studentPeriods'),all('periods'),all('scores'),all('subjects')]);const rows=GRADES.map(g=>{const kids=users.filter(u=>u.role==='student'&&u.active&&u.grade_code===g.code),valid=new Set(subjects.filter(s=>s.active&&s.grade_code===g.code).map(s=>s.id));let submitted=0,published=0,sum=0,count=0;for(const u of kids)for(let p=1;p<=4;p++){const status=personal.find(x=>x.key===pkey(u.id,p))?.state||legacy.find(x=>x.key===`${YEAR}|${g.code}|${p}`)?.state||'draft';if(status==='submitted')submitted++;if(status==='published'){published++;for(const score of scores.filter(s=>s.student_id===u.id&&s.period===p&&s.year===YEAR&&valid.has(s.subject_id))){sum+=score.score;count++;}}}return{...g,students:kids.length,submitted,published,average:count?sum/count:null};});return{overview:rows};}
if(op==='studentUpdates'){if(actor.role!=='student')fail('Solo estudiantes.');const[personal,legacy]=await Promise.all([all('studentPeriods'),all('periods')]);let unread=0,published=0;for(let p=1;p<=4;p++){const current=personal.find(s=>s.key===pkey(actor.id,p)),prior=legacy.find(s=>s.key===`${YEAR}|${actor.grade_code}|${p}`);const status=current?.state||prior?.state;if(status!=='published')continue;published++;const date=current?.published_at||prior?.published_at||'2000-01-01T00:00:00.000Z';if(!actor.last_results_seen||date>actor.last_results_seen)unread++;}return{unread:actor.delinquent?0:unread,published,debt:!!actor.delinquent};}
if(op==='studentSubjects'){if(actor.role!=='student')fail('Solo estudiantes.');return{subjects:(await all('subjects')).filter(s=>s.active&&s.grade_code===actor.grade_code).sort(subjectOrder).map(s=>s.name)};}
if(op==='markResultsRead'){if(actor.role!=='student')fail('Solo estudiantes.');if(actor.delinquent)fail('Las notas no están disponibles mientras haya mora.');actor.last_results_seen=new Date().toISOString();await put('users',actor);return{success:true};}
if(op==='studentResults'){if(actor.role!=='student')fail('Solo estudiantes.');if(actor.delinquent)return{debt:true,results:[]};const[classes,scores,individuals,legacy]=await Promise.all([all('subjects'),all('scores'),all('studentPeriods'),all('periods')]);const subs=classes.filter(s=>s.grade_code===actor.grade_code&&s.active).sort(subjectOrder);const periods=[1,2,3,4].filter(p=>(individuals.find(s=>s.key===pkey(actor.id,p))?.state||legacy.find(s=>s.key===`${YEAR}|${actor.grade_code}|${p}`)?.state)==='published');const results=subs.map(s=>({subject:s.name,values:[1,2,3,4].map(p=>{if(!periods.includes(p))return null;const note=scores.find(n=>n.key===skey(actor.id,s.id,p));return note?note.score:null;})}));return{debt:false,periods,results};}
fail('Operación no reconocida.');
}

module.exports={GRADES,SUBJECTS,YEAR,requestScope,executeOperation,all,get,put,remove,publicUser};
